version: '3.1'

services:

  api:
    container_name: nest_api
    build: .
    ports: 
      - "3001:3001"
    volumes:
      - .:/home/nestdocker
      - /home/nestdocker/node_modules

  database:
    image: mongo
    container_name: db_mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodata: 
